int		AreDoublesEqual (MrBFlt x, MrBFlt y, MrBFlt tol);
int		ChangeNumRuns (int from, int to);
int		ChangeNumChains (int from, int to);
int		DoLink (void);
int		DoLinkParm (char *parmName, char *tkn);
int		DoLset (void);
int		DoLsetParm (char *parmName, char *tkn);
int     DoPropset (void);
int     DoPropsetParm (char *parmName, char *tkn);
int		DoPrset (void);
int		DoPrsetParm (char *parmName, char *tkn);
int		DoReport (void);
int		DoReportParm (char *parmName, char *tkn);
int		DoShowMcmcTrees (void);
int		DoShowModel (void);
int		DoShowMoves (void);
int		DoShowmovesParm (char *parmName, char *tkn);
int		DoShowParams (void);
int		DoStartvals (void);
int		DoStartvalsParm (char *parmName, char *tkn);
int		DoUnlink (void);
int		FillNormalParams (safeLong *seed, int fromChain, int toChain);
int		FillRelPartsString (Param *p, char relPartString[100]);
int     FillTopologySubParams (Param *param, int chn, int state, safeLong *seed);
int		FillTreeParams (safeLong *seed, int fromChain, int toChain);
int		FreeModel (void);
int		GetEmpiricalFreqs (int *relParts, int nRelParts);
MrBFlt	*GetParamStdStateFreqs (Param *parm, int chain, int state);
MrBFlt	*GetParamSubVals (Param *parm, int chain, int state);
MrBFlt	*GetParamVals (Param *parm, int chain, int state);
Tree	*GetTree (Param *parm, int chain, int state);
Tree	*GetTreeFromIndex (int index, int chain, int state);
int		InitializeLinks (void);
int     InitializeTreeCalibrations (Tree *t);
int		Link (void);
int     SetAARates (void);
int		SetModelDefaults (void);
int		SetMoves (void);
int		SetUpAnalysis (safeLong *seed);
void	SetUpMoveTypes (void);
int		ShowModel (void);
int		Unlink (void);
int	    UpdateBmEvolLengths (Param *param, Tree *t, int chain);
int 	UpdateCppEvolLengths (Param *param, TreeNode *p, int chain);
int	    UpdateIbrEvolLengths (Param *param, Tree *t, int chain);

